version: '3.7'
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "8388:8388"
    environment:
      - METHOD=aes-256-cfb
      - PASSWORD=caroline
    restart: always
